// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protoc-gen-swagger/options/annotations.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Grpc.Gateway.ProtocGenSwagger.Options {

  /// <summary>Holder for reflection information generated from protoc-gen-swagger/options/annotations.proto</summary>
  internal static partial class AnnotationsReflection {

    #region Descriptor
    /// <summary>File descriptor for protoc-gen-swagger/options/annotations.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AnnotationsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cixwcm90b2MtZ2VuLXN3YWdnZXIvb3B0aW9ucy9hbm5vdGF0aW9ucy5wcm90",
            "bxInZ3JwYy5nYXRld2F5LnByb3RvY19nZW5fc3dhZ2dlci5vcHRpb25zGiBn",
            "b29nbGUvcHJvdG9idWYvZGVzY3JpcHRvci5wcm90bxoqcHJvdG9jLWdlbi1z",
            "d2FnZ2VyL29wdGlvbnMvb3BlbmFwaXYyLnByb3RvOmoKEW9wZW5hcGl2Ml9z",
            "d2FnZ2VyEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGJIIIAEoCzIw",
            "LmdycGMuZ2F0ZXdheS5wcm90b2NfZ2VuX3N3YWdnZXIub3B0aW9ucy5Td2Fn",
            "Z2VyOnAKE29wZW5hcGl2Ml9vcGVyYXRpb24SHi5nb29nbGUucHJvdG9idWYu",
            "TWV0aG9kT3B0aW9ucxiSCCABKAsyMi5ncnBjLmdhdGV3YXkucHJvdG9jX2dl",
            "bl9zd2FnZ2VyLm9wdGlvbnMuT3BlcmF0aW9uOmsKEG9wZW5hcGl2Ml9zY2hl",
            "bWESHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYkgggASgLMi8u",
            "Z3JwYy5nYXRld2F5LnByb3RvY19nZW5fc3dhZ2dlci5vcHRpb25zLlNjaGVt",
            "YTplCg1vcGVuYXBpdjJfdGFnEh8uZ29vZ2xlLnByb3RvYnVmLlNlcnZpY2VP",
            "cHRpb25zGJIIIAEoCzIsLmdycGMuZ2F0ZXdheS5wcm90b2NfZ2VuX3N3YWdn",
            "ZXIub3B0aW9ucy5UYWc6bAoPb3BlbmFwaXYyX2ZpZWxkEh0uZ29vZ2xlLnBy",
            "b3RvYnVmLkZpZWxkT3B0aW9ucxiSCCABKAsyMy5ncnBjLmdhdGV3YXkucHJv",
            "dG9jX2dlbl9zd2FnZ2VyLm9wdGlvbnMuSlNPTlNjaGVtYUJDWkFnaXRodWIu",
            "Y29tL2dycGMtZWNvc3lzdGVtL2dycGMtZ2F0ZXdheS9wcm90b2MtZ2VuLXN3",
            "YWdnZXIvb3B0aW9uc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, global::Grpc.Gateway.ProtocGenSwagger.Options.Openapiv2Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { AnnotationsExtensions.Openapiv2Swagger, AnnotationsExtensions.Openapiv2Operation, AnnotationsExtensions.Openapiv2Schema, AnnotationsExtensions.Openapiv2Tag, AnnotationsExtensions.Openapiv2Field }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of protoc-gen-swagger/options/annotations.proto</summary>
  internal static partial class AnnotationsExtensions {
    /// <summary>
    /// ID assigned by protobuf-global-extension-registry@google.com for grpc-gateway project.
    ///
    /// All IDs are the same, as assigned. It is okay that they are the same, as they extend
    /// different descriptor messages.
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FileOptions, global::Grpc.Gateway.ProtocGenSwagger.Options.Swagger> Openapiv2Swagger =
      new pb::Extension<global::Google.Protobuf.Reflection.FileOptions, global::Grpc.Gateway.ProtocGenSwagger.Options.Swagger>(1042, pb::FieldCodec.ForMessage(8338, global::Grpc.Gateway.ProtocGenSwagger.Options.Swagger.Parser));
    /// <summary>
    /// ID assigned by protobuf-global-extension-registry@google.com for grpc-gateway project.
    ///
    /// All IDs are the same, as assigned. It is okay that they are the same, as they extend
    /// different descriptor messages.
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, global::Grpc.Gateway.ProtocGenSwagger.Options.Operation> Openapiv2Operation =
      new pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, global::Grpc.Gateway.ProtocGenSwagger.Options.Operation>(1042, pb::FieldCodec.ForMessage(8338, global::Grpc.Gateway.ProtocGenSwagger.Options.Operation.Parser));
    /// <summary>
    /// ID assigned by protobuf-global-extension-registry@google.com for grpc-gateway project.
    ///
    /// All IDs are the same, as assigned. It is okay that they are the same, as they extend
    /// different descriptor messages.
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, global::Grpc.Gateway.ProtocGenSwagger.Options.Schema> Openapiv2Schema =
      new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, global::Grpc.Gateway.ProtocGenSwagger.Options.Schema>(1042, pb::FieldCodec.ForMessage(8338, global::Grpc.Gateway.ProtocGenSwagger.Options.Schema.Parser));
    /// <summary>
    /// ID assigned by protobuf-global-extension-registry@google.com for grpc-gateway project.
    ///
    /// All IDs are the same, as assigned. It is okay that they are the same, as they extend
    /// different descriptor messages.
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, global::Grpc.Gateway.ProtocGenSwagger.Options.Tag> Openapiv2Tag =
      new pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, global::Grpc.Gateway.ProtocGenSwagger.Options.Tag>(1042, pb::FieldCodec.ForMessage(8338, global::Grpc.Gateway.ProtocGenSwagger.Options.Tag.Parser));
    /// <summary>
    /// ID assigned by protobuf-global-extension-registry@google.com for grpc-gateway project.
    ///
    /// All IDs are the same, as assigned. It is okay that they are the same, as they extend
    /// different descriptor messages.
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, global::Grpc.Gateway.ProtocGenSwagger.Options.JSONSchema> Openapiv2Field =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, global::Grpc.Gateway.ProtocGenSwagger.Options.JSONSchema>(1042, pb::FieldCodec.ForMessage(8338, global::Grpc.Gateway.ProtocGenSwagger.Options.JSONSchema.Parser));
  }

}

#endregion Designer generated code
