/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling

namespace Jaeger.Thrift.Agent.Zipkin
{
  public partial class ZipkinCollector
  {
    public interface IAsync
    {
      global::System.Threading.Tasks.Task<List<global::Jaeger.Thrift.Agent.Zipkin.Response>> submitZipkinBatchAsync(List<global::Jaeger.Thrift.Agent.Zipkin.Span> spans, CancellationToken cancellationToken = default);

    }


    public class Client : TBaseClient, IDisposable, IAsync
    {
      public Client(TProtocol protocol) : this(protocol, protocol)
      {
      }

      public Client(TProtocol inputProtocol, TProtocol outputProtocol) : base(inputProtocol, outputProtocol)      {
      }
      public async global::System.Threading.Tasks.Task<List<global::Jaeger.Thrift.Agent.Zipkin.Response>> submitZipkinBatchAsync(List<global::Jaeger.Thrift.Agent.Zipkin.Span> spans, CancellationToken cancellationToken = default)
      {
        await OutputProtocol.WriteMessageBeginAsync(new TMessage("submitZipkinBatch", TMessageType.Call, SeqId), cancellationToken);
        
        var args = new InternalStructs.submitZipkinBatchArgs() {
          Spans = spans,
        };
        
        await args.WriteAsync(OutputProtocol, cancellationToken);
        await OutputProtocol.WriteMessageEndAsync(cancellationToken);
        await OutputProtocol.Transport.FlushAsync(cancellationToken);
        
        var msg = await InputProtocol.ReadMessageBeginAsync(cancellationToken);
        if (msg.Type == TMessageType.Exception)
        {
          var x = await TApplicationException.ReadAsync(InputProtocol, cancellationToken);
          await InputProtocol.ReadMessageEndAsync(cancellationToken);
          throw x;
        }

        var result = new InternalStructs.submitZipkinBatchResult();
        await result.ReadAsync(InputProtocol, cancellationToken);
        await InputProtocol.ReadMessageEndAsync(cancellationToken);
        if (result.__isset.success)
        {
          return result.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "submitZipkinBatch failed: unknown result");
      }

    }

    public class AsyncProcessor : ITAsyncProcessor
    {
      private readonly IAsync _iAsync;
      private readonly ILogger<AsyncProcessor> _logger;

      public AsyncProcessor(IAsync iAsync, ILogger<AsyncProcessor> logger = default)
      {
        _iAsync = iAsync ?? throw new ArgumentNullException(nameof(iAsync));
        _logger = logger;
        processMap_["submitZipkinBatch"] = submitZipkinBatch_ProcessAsync;
      }

      protected delegate global::System.Threading.Tasks.Task ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken);
      protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

      public async Task<bool> ProcessAsync(TProtocol iprot, TProtocol oprot)
      {
        return await ProcessAsync(iprot, oprot, CancellationToken.None);
      }

      public async Task<bool> ProcessAsync(TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        try
        {
          var msg = await iprot.ReadMessageBeginAsync(cancellationToken);

          processMap_.TryGetValue(msg.Name, out ProcessFunction fn);

          if (fn == null)
          {
            await TProtocolUtil.SkipAsync(iprot, TType.Struct, cancellationToken);
            await iprot.ReadMessageEndAsync(cancellationToken);
            var x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
            await oprot.WriteMessageBeginAsync(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID), cancellationToken);
            await x.WriteAsync(oprot, cancellationToken);
            await oprot.WriteMessageEndAsync(cancellationToken);
            await oprot.Transport.FlushAsync(cancellationToken);
            return true;
          }

          await fn(msg.SeqID, iprot, oprot, cancellationToken);

        }
        catch (IOException)
        {
          return false;
        }

        return true;
      }

      public async global::System.Threading.Tasks.Task submitZipkinBatch_ProcessAsync(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        var args = new InternalStructs.submitZipkinBatchArgs();
        await args.ReadAsync(iprot, cancellationToken);
        await iprot.ReadMessageEndAsync(cancellationToken);
        var result = new InternalStructs.submitZipkinBatchResult();
        try
        {
          result.Success = await _iAsync.submitZipkinBatchAsync(args.Spans, cancellationToken);
          await oprot.WriteMessageBeginAsync(new TMessage("submitZipkinBatch", TMessageType.Reply, seqid), cancellationToken); 
          await result.WriteAsync(oprot, cancellationToken);
        }
        catch (TTransportException)
        {
          throw;
        }
        catch (Exception ex)
        {
          var sErr = $"Error occurred in {GetType().FullName}: {ex.Message}";
          if(_logger != null)
            _logger.LogError(ex, sErr);
          else
            Console.Error.WriteLine(sErr);
          var x = new TApplicationException(TApplicationException.ExceptionType.InternalError," Internal error.");
          await oprot.WriteMessageBeginAsync(new TMessage("submitZipkinBatch", TMessageType.Exception, seqid), cancellationToken);
          await x.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteMessageEndAsync(cancellationToken);
        await oprot.Transport.FlushAsync(cancellationToken);
      }

    }

    public class InternalStructs
    {

      public partial class submitZipkinBatchArgs : TBase
      {
        private List<global::Jaeger.Thrift.Agent.Zipkin.Span> _spans;

        public List<global::Jaeger.Thrift.Agent.Zipkin.Span> Spans
        {
          get
          {
            return _spans;
          }
          set
          {
            __isset.spans = true;
            this._spans = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool spans;
        }

        public submitZipkinBatchArgs()
        {
        }

        public submitZipkinBatchArgs DeepCopy()
        {
          var tmp18 = new submitZipkinBatchArgs();
          if((Spans != null) && __isset.spans)
          {
            tmp18.Spans = this.Spans.DeepCopy();
          }
          tmp18.__isset.spans = this.__isset.spans;
          return tmp18;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 1:
                  if (field.Type == TType.List)
                  {
                    {
                      TList _list19 = await iprot.ReadListBeginAsync(cancellationToken);
                      Spans = new List<global::Jaeger.Thrift.Agent.Zipkin.Span>(_list19.Count);
                      for(int _i20 = 0; _i20 < _list19.Count; ++_i20)
                      {
                        global::Jaeger.Thrift.Agent.Zipkin.Span _elem21;
                        _elem21 = new global::Jaeger.Thrift.Agent.Zipkin.Span();
                        await _elem21.ReadAsync(iprot, cancellationToken);
                        Spans.Add(_elem21);
                      }
                      await iprot.ReadListEndAsync(cancellationToken);
                    }
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var struc = new TStruct("submitZipkinBatch_args");
            await oprot.WriteStructBeginAsync(struc, cancellationToken);
            var field = new TField();
            if((Spans != null) && __isset.spans)
            {
              field.Name = "spans";
              field.Type = TType.List;
              field.ID = 1;
              await oprot.WriteFieldBeginAsync(field, cancellationToken);
              {
                await oprot.WriteListBeginAsync(new TList(TType.Struct, Spans.Count), cancellationToken);
                foreach (global::Jaeger.Thrift.Agent.Zipkin.Span _iter22 in Spans)
                {
                  await _iter22.WriteAsync(oprot, cancellationToken);
                }
                await oprot.WriteListEndAsync(cancellationToken);
              }
              await oprot.WriteFieldEndAsync(cancellationToken);
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is submitZipkinBatchArgs other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.spans == other.__isset.spans) && ((!__isset.spans) || (TCollections.Equals(Spans, other.Spans))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((Spans != null) && __isset.spans)
            {
              hashcode = (hashcode * 397) + TCollections.GetHashCode(Spans);
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var sb = new StringBuilder("submitZipkinBatch_args(");
          int tmp23 = 0;
          if((Spans != null) && __isset.spans)
          {
            if(0 < tmp23++) { sb.Append(", "); }
            sb.Append("Spans: ");
            Spans.ToString(sb);
          }
          sb.Append(')');
          return sb.ToString();
        }
      }


      public partial class submitZipkinBatchResult : TBase
      {
        private List<global::Jaeger.Thrift.Agent.Zipkin.Response> _success;

        public List<global::Jaeger.Thrift.Agent.Zipkin.Response> Success
        {
          get
          {
            return _success;
          }
          set
          {
            __isset.success = true;
            this._success = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool success;
        }

        public submitZipkinBatchResult()
        {
        }

        public submitZipkinBatchResult DeepCopy()
        {
          var tmp24 = new submitZipkinBatchResult();
          if((Success != null) && __isset.success)
          {
            tmp24.Success = this.Success.DeepCopy();
          }
          tmp24.__isset.success = this.__isset.success;
          return tmp24;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 0:
                  if (field.Type == TType.List)
                  {
                    {
                      TList _list25 = await iprot.ReadListBeginAsync(cancellationToken);
                      Success = new List<global::Jaeger.Thrift.Agent.Zipkin.Response>(_list25.Count);
                      for(int _i26 = 0; _i26 < _list25.Count; ++_i26)
                      {
                        global::Jaeger.Thrift.Agent.Zipkin.Response _elem27;
                        _elem27 = new global::Jaeger.Thrift.Agent.Zipkin.Response();
                        await _elem27.ReadAsync(iprot, cancellationToken);
                        Success.Add(_elem27);
                      }
                      await iprot.ReadListEndAsync(cancellationToken);
                    }
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var struc = new TStruct("submitZipkinBatch_result");
            await oprot.WriteStructBeginAsync(struc, cancellationToken);
            var field = new TField();

            if(this.__isset.success)
            {
              if (Success != null)
              {
                field.Name = "Success";
                field.Type = TType.List;
                field.ID = 0;
                await oprot.WriteFieldBeginAsync(field, cancellationToken);
                {
                  await oprot.WriteListBeginAsync(new TList(TType.Struct, Success.Count), cancellationToken);
                  foreach (global::Jaeger.Thrift.Agent.Zipkin.Response _iter28 in Success)
                  {
                    await _iter28.WriteAsync(oprot, cancellationToken);
                  }
                  await oprot.WriteListEndAsync(cancellationToken);
                }
                await oprot.WriteFieldEndAsync(cancellationToken);
              }
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is submitZipkinBatchResult other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.success == other.__isset.success) && ((!__isset.success) || (TCollections.Equals(Success, other.Success))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((Success != null) && __isset.success)
            {
              hashcode = (hashcode * 397) + TCollections.GetHashCode(Success);
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var sb = new StringBuilder("submitZipkinBatch_result(");
          int tmp29 = 0;
          if((Success != null) && __isset.success)
          {
            if(0 < tmp29++) { sb.Append(", "); }
            sb.Append("Success: ");
            Success.ToString(sb);
          }
          sb.Append(')');
          return sb.ToString();
        }
      }

    }

  }
}
