// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: collector.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Jaeger.ApiV2 {

  /// <summary>Holder for reflection information generated from collector.proto</summary>
  public static partial class CollectorReflection {

    #region Descriptor
    /// <summary>File descriptor for collector.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CollectorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9jb2xsZWN0b3IucHJvdG8SDWphZWdlci5hcGlfdjIaC21vZGVsLnByb3Rv",
            "GhRnb2dvcHJvdG8vZ29nby5wcm90bxocZ29vZ2xlL2FwaS9hbm5vdGF0aW9u",
            "cy5wcm90bxoscHJvdG9jLWdlbi1zd2FnZ2VyL29wdGlvbnMvYW5ub3RhdGlv",
            "bnMucHJvdG8iPQoQUG9zdFNwYW5zUmVxdWVzdBIpCgViYXRjaBgBIAEoCzIU",
            "LmphZWdlci5hcGlfdjIuQmF0Y2hCBMjeHwAiEwoRUG9zdFNwYW5zUmVzcG9u",
            "c2UyfAoQQ29sbGVjdG9yU2VydmljZRJoCglQb3N0U3BhbnMSHy5qYWVnZXIu",
            "YXBpX3YyLlBvc3RTcGFuc1JlcXVlc3QaIC5qYWVnZXIuYXBpX3YyLlBvc3RT",
            "cGFuc1Jlc3BvbnNlIhiC0+STAhIiDS9hcGkvdjIvc3BhbnM6ASpCdgoXaW8u",
            "amFlZ2VydHJhY2luZy5hcGlfdjJaBmFwaV92MsjiHgHQ4h4B4OIeAcDjHgGS",
            "QUISBTIDMS4wKgIBAnI1CgpKYWVnZXIgQVBJEidodHRwczovL2dpdGh1Yi5j",
            "b20vamFlZ2VydHJhY2luZy9qYWVnZXJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Jaeger.ApiV2.ModelReflection.Descriptor, global::Gogoproto.GogoReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, global::Grpc.Gateway.ProtocGenSwagger.Options.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Jaeger.ApiV2.PostSpansRequest), global::Jaeger.ApiV2.PostSpansRequest.Parser, new[]{ "Batch" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Jaeger.ApiV2.PostSpansResponse), global::Jaeger.ApiV2.PostSpansResponse.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PostSpansRequest : pb::IMessage<PostSpansRequest> {
    private static readonly pb::MessageParser<PostSpansRequest> _parser = new pb::MessageParser<PostSpansRequest>(() => new PostSpansRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PostSpansRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Jaeger.ApiV2.CollectorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSpansRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSpansRequest(PostSpansRequest other) : this() {
      batch_ = other.batch_ != null ? other.batch_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSpansRequest Clone() {
      return new PostSpansRequest(this);
    }

    /// <summary>Field number for the "batch" field.</summary>
    public const int BatchFieldNumber = 1;
    private global::Jaeger.ApiV2.Batch batch_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Jaeger.ApiV2.Batch Batch {
      get { return batch_; }
      set {
        batch_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PostSpansRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PostSpansRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Batch, other.Batch)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (batch_ != null) hash ^= Batch.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (batch_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Batch);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (batch_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Batch);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PostSpansRequest other) {
      if (other == null) {
        return;
      }
      if (other.batch_ != null) {
        if (batch_ == null) {
          Batch = new global::Jaeger.ApiV2.Batch();
        }
        Batch.MergeFrom(other.Batch);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (batch_ == null) {
              Batch = new global::Jaeger.ApiV2.Batch();
            }
            input.ReadMessage(Batch);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PostSpansResponse : pb::IMessage<PostSpansResponse> {
    private static readonly pb::MessageParser<PostSpansResponse> _parser = new pb::MessageParser<PostSpansResponse>(() => new PostSpansResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PostSpansResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Jaeger.ApiV2.CollectorReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSpansResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSpansResponse(PostSpansResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSpansResponse Clone() {
      return new PostSpansResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PostSpansResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PostSpansResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PostSpansResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
