/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Jaeger.Thrift.Crossdock
{
  public enum Transport
  {
    HTTP = 0,
    TCHANNEL = 1,
    DUMMY = 2,
  }
}
