/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

using System.Text;
using System.Threading;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling

namespace Jaeger.Thrift.Crossdock
{

  public partial class JoinTraceRequest : TBase
  {
    private global::Jaeger.Thrift.Crossdock.Downstream _downstream;

    public string ServerRole { get; set; }

    public global::Jaeger.Thrift.Crossdock.Downstream Downstream
    {
      get
      {
        return _downstream;
      }
      set
      {
        __isset.downstream = true;
        this._downstream = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool downstream;
    }

    public JoinTraceRequest()
    {
    }

    public JoinTraceRequest(string serverRole) : this()
    {
      this.ServerRole = serverRole;
    }

    public JoinTraceRequest DeepCopy()
    {
      var tmp4 = new JoinTraceRequest();
      if((ServerRole != null))
      {
        tmp4.ServerRole = this.ServerRole;
      }
      if((Downstream != null) && __isset.downstream)
      {
        tmp4.Downstream = (global::Jaeger.Thrift.Crossdock.Downstream)this.Downstream.DeepCopy();
      }
      tmp4.__isset.downstream = this.__isset.downstream;
      return tmp4;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_serverRole = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                ServerRole = await iprot.ReadStringAsync(cancellationToken);
                isset_serverRole = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.Struct)
              {
                Downstream = new global::Jaeger.Thrift.Crossdock.Downstream();
                await Downstream.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_serverRole)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("JoinTraceRequest");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        if((ServerRole != null))
        {
          field.Name = "serverRole";
          field.Type = TType.String;
          field.ID = 1;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(ServerRole, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Downstream != null) && __isset.downstream)
        {
          field.Name = "downstream";
          field.Type = TType.Struct;
          field.ID = 2;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await Downstream.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is JoinTraceRequest other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return System.Object.Equals(ServerRole, other.ServerRole)
        && ((__isset.downstream == other.__isset.downstream) && ((!__isset.downstream) || (System.Object.Equals(Downstream, other.Downstream))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((ServerRole != null))
        {
          hashcode = (hashcode * 397) + ServerRole.GetHashCode();
        }
        if((Downstream != null) && __isset.downstream)
        {
          hashcode = (hashcode * 397) + Downstream.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var sb = new StringBuilder("JoinTraceRequest(");
      if((ServerRole != null))
      {
        sb.Append(", ServerRole: ");
        ServerRole.ToString(sb);
      }
      if((Downstream != null) && __isset.downstream)
      {
        sb.Append(", Downstream: ");
        Downstream.ToString(sb);
      }
      sb.Append(')');
      return sb.ToString();
    }
  }

}
