/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Jaeger.Thrift
{
  public enum SpanRefType
  {
    CHILD_OF = 0,
    FOLLOWS_FROM = 1,
  }
}
