// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: sampling.proto
// </auto-generated>
// Original file comments:
// Copyright (c) 2019 The Jaeger Authors.
// Copyright (c) 2018 Uber Technologies, Inc.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Jaeger.ApiV2 {
  public static partial class SamplingManager
  {
    static readonly string __ServiceName = "jaeger.api_v2.SamplingManager";

    static readonly grpc::Marshaller<global::Jaeger.ApiV2.SamplingStrategyParameters> __Marshaller_jaeger_api_v2_SamplingStrategyParameters = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Jaeger.ApiV2.SamplingStrategyParameters.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Jaeger.ApiV2.SamplingStrategyResponse> __Marshaller_jaeger_api_v2_SamplingStrategyResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Jaeger.ApiV2.SamplingStrategyResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Jaeger.ApiV2.SamplingStrategyParameters, global::Jaeger.ApiV2.SamplingStrategyResponse> __Method_GetSamplingStrategy = new grpc::Method<global::Jaeger.ApiV2.SamplingStrategyParameters, global::Jaeger.ApiV2.SamplingStrategyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSamplingStrategy",
        __Marshaller_jaeger_api_v2_SamplingStrategyParameters,
        __Marshaller_jaeger_api_v2_SamplingStrategyResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Jaeger.ApiV2.SamplingReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SamplingManager</summary>
    [grpc::BindServiceMethod(typeof(SamplingManager), "BindService")]
    public abstract partial class SamplingManagerBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Jaeger.ApiV2.SamplingStrategyResponse> GetSamplingStrategy(global::Jaeger.ApiV2.SamplingStrategyParameters request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SamplingManager</summary>
    public partial class SamplingManagerClient : grpc::ClientBase<SamplingManagerClient>
    {
      /// <summary>Creates a new client for SamplingManager</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SamplingManagerClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SamplingManager that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SamplingManagerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SamplingManagerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SamplingManagerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Jaeger.ApiV2.SamplingStrategyResponse GetSamplingStrategy(global::Jaeger.ApiV2.SamplingStrategyParameters request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSamplingStrategy(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Jaeger.ApiV2.SamplingStrategyResponse GetSamplingStrategy(global::Jaeger.ApiV2.SamplingStrategyParameters request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSamplingStrategy, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Jaeger.ApiV2.SamplingStrategyResponse> GetSamplingStrategyAsync(global::Jaeger.ApiV2.SamplingStrategyParameters request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSamplingStrategyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Jaeger.ApiV2.SamplingStrategyResponse> GetSamplingStrategyAsync(global::Jaeger.ApiV2.SamplingStrategyParameters request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSamplingStrategy, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SamplingManagerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SamplingManagerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SamplingManagerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetSamplingStrategy, serviceImpl.GetSamplingStrategy).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SamplingManagerBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetSamplingStrategy, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Jaeger.ApiV2.SamplingStrategyParameters, global::Jaeger.ApiV2.SamplingStrategyResponse>(serviceImpl.GetSamplingStrategy));
    }

  }
}
#endregion
