/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

using System.Text;
using System.Threading;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling

namespace Jaeger.Thrift
{

  public partial class SpanRef : TBase
  {

    /// <summary>
    /// 
    /// <seealso cref="global::Jaeger.Thrift.SpanRefType"/>
    /// </summary>
    public global::Jaeger.Thrift.SpanRefType RefType { get; set; }

    public long TraceIdLow { get; set; }

    public long TraceIdHigh { get; set; }

    public long SpanId { get; set; }

    public SpanRef()
    {
    }

    public SpanRef(global::Jaeger.Thrift.SpanRefType refType, long traceIdLow, long traceIdHigh, long spanId) : this()
    {
      this.RefType = refType;
      this.TraceIdLow = traceIdLow;
      this.TraceIdHigh = traceIdHigh;
      this.SpanId = spanId;
    }

    public SpanRef DeepCopy()
    {
      var tmp8 = new SpanRef();
      tmp8.RefType = this.RefType;
      tmp8.TraceIdLow = this.TraceIdLow;
      tmp8.TraceIdHigh = this.TraceIdHigh;
      tmp8.SpanId = this.SpanId;
      return tmp8;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_refType = false;
        bool isset_traceIdLow = false;
        bool isset_traceIdHigh = false;
        bool isset_spanId = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32)
              {
                RefType = (global::Jaeger.Thrift.SpanRefType)await iprot.ReadI32Async(cancellationToken);
                isset_refType = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.I64)
              {
                TraceIdLow = await iprot.ReadI64Async(cancellationToken);
                isset_traceIdLow = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.I64)
              {
                TraceIdHigh = await iprot.ReadI64Async(cancellationToken);
                isset_traceIdHigh = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.I64)
              {
                SpanId = await iprot.ReadI64Async(cancellationToken);
                isset_spanId = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_refType)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_traceIdLow)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_traceIdHigh)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_spanId)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("SpanRef");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        field.Name = "refType";
        field.Type = TType.I32;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI32Async((int)RefType, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "traceIdLow";
        field.Type = TType.I64;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI64Async(TraceIdLow, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "traceIdHigh";
        field.Type = TType.I64;
        field.ID = 3;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI64Async(TraceIdHigh, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "spanId";
        field.Type = TType.I64;
        field.ID = 4;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI64Async(SpanId, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is SpanRef other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return System.Object.Equals(RefType, other.RefType)
        && System.Object.Equals(TraceIdLow, other.TraceIdLow)
        && System.Object.Equals(TraceIdHigh, other.TraceIdHigh)
        && System.Object.Equals(SpanId, other.SpanId);
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        hashcode = (hashcode * 397) + RefType.GetHashCode();
        hashcode = (hashcode * 397) + TraceIdLow.GetHashCode();
        hashcode = (hashcode * 397) + TraceIdHigh.GetHashCode();
        hashcode = (hashcode * 397) + SpanId.GetHashCode();
      }
      return hashcode;
    }

    public override string ToString()
    {
      var sb = new StringBuilder("SpanRef(");
      sb.Append(", RefType: ");
      RefType.ToString(sb);
      sb.Append(", TraceIdLow: ");
      TraceIdLow.ToString(sb);
      sb.Append(", TraceIdHigh: ");
      TraceIdHigh.ToString(sb);
      sb.Append(", SpanId: ");
      SpanId.ToString(sb);
      sb.Append(')');
      return sb.ToString();
    }
  }

}
